# Generated by Django 5.2.12 on 2026-03-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_feedback_instructor_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
