# Generated by Django 5.2.12 on 2026-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_feedback_instructor_alter_videoprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
