# Generated by Django 5.2.12 on 2026-03-30 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_studentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='studentsubmission',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
