# Generated by Django 5.2.12 on 2026-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_studentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='created_at',
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
