# Generated by Django 5.2.12 on 2026-04-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_studentsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Question',
        ),
    ]
