# Generated by Django 5.2.12 on 2026-04-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='current_time',
            field=models.FloatField(default=0),
        ),
    ]
