# Generated by Django 5.2.12 on 2026-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profiles/'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
